name = "olikit-datasets"
compatibility_date = "2024-05-01"

# D1 Database Bindings
[[d1_databases]]
binding = "SALARY_DB"
database_name = "olikit-salary-db"
database_id = ""

[[d1_databases]]
binding = "TAX_DB"
database_name = "olikit-tax-db"
database_id = ""

[[d1_databases]]
binding = "COST_OF_LIVING_DB"
database_name = "olikit-col-db"
database_id = ""
